In [15]:
import pandas as pd
import numpy as np
import os 
from pathlib import Path

In [16]:
seeds = [1, 2, 3, 4, 5]

model_names_and_params = {'gplvm_cv_results':'_latentdim_5_inducing_50_maskseed_42', 
                          'gplvm_ssvi_case_1_cv_results':'_latentdim_6_inducing_50_maskseed_42_batchsize_32',
                          'knn_cv_results':'_neighbours_5_maskseed_42'
                          } 
all_results = []
for model_name, params in model_names_and_params.items():
    for seed in seeds:
        file_path = Path(os.getcwd()) / 'results' / f"{model_name}_seed_{seed}{params}.csv"
        try:
            df = pd.read_csv(file_path)
            df['model'] = model_name
            df['seed'] = seed
            all_results.append(df)
        except FileNotFoundError:
            print(f"File not found: {file_path}")
            continue
    
    
all_results = pd.concat(all_results, ignore_index=True)

File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/gplvm_ssvi_case_1_cv_results_seed_2_latentdim_6_inducing_50_maskseed_42_batchsize_32.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/gplvm_ssvi_case_1_cv_results_seed_3_latentdim_6_inducing_50_maskseed_42_batchsize_32.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/gplvm_ssvi_case_1_cv_results_seed_4_latentdim_6_inducing_50_maskseed_42_batchsize_32.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/gplvm_ssvi_case_1_cv_results_seed_5_latentdim_6_inducing_50_maskseed_42_batchsize_32.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/knn_cv_results_seed_1_neighbours_5_maskseed_42.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/knn_cv_results_seed_2_neighbours_5_maskseed_42.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/knn_cv_results_seed_3_neighbours_5_maskseed_42.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/knn_cv_results_seed_4_neighbours_5_maskseed_42.csv
File not found: /Users/rsedgwick/conditional_overlaping_gaussian_processes/gplvm_missing_data/results/knn_cv_results_seed_5_neighbours_5_maskseed_42.csv

In [17]:
all_results

,fold,rmse_dim_train_1,rmse_dim_train_2,rmse_dim_train_3,rmse_dim_train_4,rmse_dim_train_5,rmse_dim_train_6,rmse_dim_train_7,rmse_dim_train_8,rmse_dim_train_9,...,nlpd_dim_test_5,nlpd_dim_test_6,nlpd_dim_test_7,nlpd_dim_test_8,nlpd_dim_test_9,nlpd_dim_test_10,total_rmse_test,total_nlpd_test,model,seed
0,0,0.323042,0.294672,0.253055,0.318260,0.597932,0.650554,0.991951,0.965552,0.996417,...,0.984119,1.084248,1.927232,1.312914,1.414030,1.277597,0.710095,1.023846,gplvm_cv_results,1
1,1,0.382646,0.301757,0.270650,0.281017,0.624491,0.698244,0.993799,0.974867,0.999331,...,0.974271,1.211350,1.391123,1.598409,1.900441,1.843282,0.791671,1.102193,gplvm_cv_results,1
2,2,0.312648,0.293701,0.280025,0.309911,0.640937,0.726087,0.998664,0.953523,0.998042,...,0.942022,1.325293,1.486790,1.284571,1.341893,1.687741,0.728069,1.062021,gplvm_cv_results,1
3,3,0.308531,0.268156,0.232005,0.341261,0.594449,0.670698,0.999245,0.936204,0.999283,...,0.933551,1.060421,1.257192,1.677356,1.171585,1.393617,0.658663,0.983226,gplvm_cv_results,1
4,4,0.308883,0.271354,0.329554,0.294274,0.547064,0.648552,0.997227,0.946897,0.995961,...,1.245436,1.178211,1.234200,1.157928,1.583704,1.096938,0.635705,0.960787,gplvm_cv_results,1
5,0,0.293595,0.307733,0.244131,0.321225,0.640676,0.650891,0.991406,0.968044,0.996899,...,1.003325,0.980186,1.931769,1.334071,1.416183,1.279868,0.733565,1.133644,gplvm_cv_results,2
6,1,0.383963,0.338124,0.258455,0.293925,0.624147,0.742382,0.994213,0.974063,0.998403,...,1.066837,1.315680,1.391591,1.600743,1.895775,1.842492,0.815788,1.146310,gplvm_cv_results,2
7,2,0.312857,0.303665,0.272530,0.338849,0.639465,0.720733,0.997885,0.956077,0.997655,...,0.937651,1.324432,1.493536,1.287293,1.339117,1.687227,0.744298,1.121176,gplvm_cv_results,2
8,3,0.287646,0.238866,0.266210,0.353518,0.649422,0.719472,0.999376,0.943117,0.999771,...,1.104682,1.126110,1.259179,1.686639,1.171127,1.400409,0.683933,1.029487,gplvm_cv_results,2
9,4,0.293935,0.284056,0.315167,0.299373,0.549151,0.633779,0.996733,0.951591,0.995637,...,1.078120,1.071889,1.234719,1.171282,1.589687,1.094894,0.636578,0.995040,gplvm_cv_results,2
10,0,0.328168,0.274923,0.275592,0.334607,0.621958,0.683618,0.995411,0.965472,0.997612,...,1.072854,1.045940,1.928450,1.318663,1.410610,1.279158,0.709899,1.011064,gplvm_cv_results,3
11,1,0.387419,0.324715,0.267182,0.320913,0.609941,0.731485,0.996072,0.980100,1.000376,...,1.032244,1.217004,1.396125,1.596990,1.901570,1.836931,0.804713,1.130239,gplvm_cv_results,3
12,2,0.322180,0.309975,0.291740,0.301378,0.607079,0.701519,0.996884,0.953561,0.998139,...,0.900827,1.291763,1.493880,1.278760,1.340916,1.686890,0.720428,1.040826,gplvm_cv_results,3
13,3,0.282509,0.251822,0.273356,0.356800,0.622650,0.689125,0.998700,0.945479,0.999410,...,1.049384,1.121566,1.259017,1.688334,1.171306,1.397709,0.689821,1.089543,gplvm_cv_results,3
14,4,0.292717,0.277178,0.337196,0.292551,0.594661,0.658663,0.999072,0.955103,0.994512,...,1.252478,1.196579,1.231520,1.161622,1.581602,1.094778,0.637018,0.970709,gplvm_cv_results,3
15,0,0.333738,0.304110,0.260011,0.344302,0.659238,0.695401,0.992796,0.964371,0.995068,...,0.948443,1.068206,1.928648,1.327292,1.414838,1.280202,0.733493,1.125617,gplvm_cv_results,4
16,1,0.373946,0.312222,0.248962,0.305021,0.600289,0.695742,0.995442,0.975907,0.998810,...,1.079312,1.275534,1.391055,1.601183,1.897683,1.836189,0.805141,1.122935,gplvm_cv_results,4
17,2,0.296504,0.323281,0.255094,0.317707,0.577879,0.661123,0.997047,0.959484,0.998718,...,0.957433,1.262782,1.492271,1.282018,1.341683,1.688203,0.727119,1.070262,gplvm_cv_results,4
18,3,0.296022,0.266803,0.245377,0.364396,0.620305,0.702994,0.999090,0.936209,0.998947,...,0.994679,1.117519,1.259729,1.690696,1.171632,1.392627,0.678619,1.042090,gplvm_cv_results,4
19,4,0.304764,0.259729,0.336927,0.269925,0.569927,0.638771,0.996295,0.943520,0.997060,...,1.408161,1.225529,1.230545,1.176938,1.584875,1.095823,0.670541,1.073662,gplvm_cv_results,4
20,0,0.313225,0.279150,0.272418,0.335870,0.633868,0.674354,0.991732,0.968271,0.997216,...,1.075258,1.016558,1.922814,1.325641,1.415472,1.279040,0.716151,1.036594,gplvm_cv_results,5
21,1,0.367992,0.312196,0.261287,0.307865,0.621693,0.711622,0.995201,0.979725,1.000147,...,0.966648,1.197375,1.387739,1.601510,1.897507,1.835012,0.789806,1.083404,gplvm_cv_results,5
22,2,0.297767,0.316853,0.245570,0.331702,0.620248,0.683136,0.994853,0.954813,0.997254,...,0.871175,1.141598,1.485361,1.278503,1.342081,1.688351,0.712421,1.042383,gplvm_cv_results,5
23,3,0.287690,0.241875,0.281749,0.325657,0.652807,0.692344,0.999085,0.934204,1.000148,...,0.962522,1.101506,1.257894,1.688352,1.170082,1.397699,0.671679,1.030760,gplvm_cv_results,5
24,4,0.297064,0.254878,0.347774,0.271447,0.541138,0.588496,0.994386,0.947817,0.995862,...,1.178150,1.324177,1.228326,1.152702,1.581043,1.095887,0.657537,1.067498,gplvm_cv_results,5
25,0,0.999692,0.984641,0.984855,0.979530,0.993063,0.985324,1.002654,1.000339,1.003227,...,1.487974,1.290528,1.882543,1.394074,1.415878,1.287346,1.008570,1.441538,gplvm_ssvi_case_1_cv_results,1
26,1,0.980929,0.991109,0.997514,0.991424,0.984664,0.998593,1.001743,1.001648,0.999058,...,1.464436,1.634404,1.384489,1.662517,1.872550,1.788530,1.144037,1.573420,gplvm_ssvi_case_1_cv_results,1
27,2,0.671106,0.750291,0.715886,0.771893,0.818635,0.834075,0.998120,0.966519,0.994817,...,1.193743,1.468317,1.502393,1.281062,1.343814,1.681535,0.932482,1.364611,gplvm_ssvi_case_1_cv_results,1
28,3,0.652056,0.580779,0.517605,0.667019,0.747927,0.868043,0.997037,0.925191,1.003292,...,1.203522,1.207063,1.246001,1.666179,1.155275,1.412130,0.820345,1.263795,gplvm_ssvi_case_1_cv_results,1
29,4,0.603817,0.582935,0.642372,0.558279,0.690627,0.742960,0.999674,0.957928,0.992538,...,1.231354,1.322579,1.219014,1.138384,1.606070,1.055790,0.754239,1.206722,gplvm_ssvi_case_1_cv_results,1

In [18]:
# for each seed and model, get the mean rmse and nlpd and print in a nice dataframe
summary_results = all_results.groupby(['model', 'seed']).agg({'total_rmse_test':'mean', 'total_nlpd_test':'mean', 'total_rmse_train':'mean', 'total_nlpd_train':'mean'}).reset_index()
summary_results_std = all_results.groupby(['model', 'seed']).agg({'total_rmse_test':'std', 'total_nlpd_test':'std', 'total_rmse_train':'std', 'total_nlpd_train':'std'}).reset_index()


summary_results

,model,seed,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
0,gplvm_cv_results,1,0.704841,1.026415,0.642103,0.845617
1,gplvm_cv_results,2,0.722832,1.085131,0.646564,0.852760
2,gplvm_cv_results,3,0.712376,1.048476,0.647683,0.857115
3,gplvm_cv_results,4,0.722983,1.086913,0.643600,0.848483
4,gplvm_cv_results,5,0.709519,1.052128,0.642155,0.845188
5,gplvm_ssvi_case_1_cv_results,1,0.931935,1.370017,0.882467,1.319196

In [19]:
summary_results_std

,model,seed,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
0,gplvm_cv_results,1,0.061276,0.057422,0.008947,0.017172
1,gplvm_cv_results,2,0.067398,0.068206,0.011075,0.021566
2,gplvm_cv_results,3,0.060796,0.063003,0.008644,0.018807
3,gplvm_cv_results,4,0.053842,0.036255,0.009410,0.019050
4,gplvm_cv_results,5,0.051557,0.022401,0.011704,0.022565
5,gplvm_ssvi_case_1_cv_results,1,0.154020,0.145315,0.105503,0.092467

In [20]:
all_results.groupby('model').agg({'total_rmse_test':'mean', 'total_nlpd_test':'mean', 'total_rmse_train':'mean', 'total_nlpd_train':'mean'})

,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
model,,,,
gplvm_cv_results,0.714510,1.059813,0.644421,0.849833
gplvm_ssvi_case_1_cv_results,0.931935,1.370017,0.882467,1.319196

In [21]:
summary_results_incl_dims =all_results.groupby(['model', 'seed']).mean().reset_index()

summary_results_incl_dims

,model,seed,fold,rmse_dim_train_1,rmse_dim_train_2,rmse_dim_train_3,rmse_dim_train_4,rmse_dim_train_5,rmse_dim_train_6,rmse_dim_train_7,...,nlpd_dim_test_3,nlpd_dim_test_4,nlpd_dim_test_5,nlpd_dim_test_6,nlpd_dim_test_7,nlpd_dim_test_8,nlpd_dim_test_9,nlpd_dim_test_10,total_rmse_test,total_nlpd_test
0,gplvm_cv_results,1,2.0,0.327150,0.285928,0.273058,0.308945,0.600975,0.678827,0.996177,...,0.516077,0.518756,1.015880,1.171905,1.459307,1.406236,1.482331,1.459835,0.704841,1.026415
1,gplvm_cv_results,2,2.0,0.314399,0.294489,0.271299,0.321378,0.620572,0.693452,0.995923,...,0.704425,0.688399,1.038123,1.163659,1.462159,1.416006,1.482378,1.460978,0.722832,1.085131
2,gplvm_cv_results,3,2.0,0.322599,0.287723,0.289013,0.321250,0.611258,0.692882,0.997228,...,0.462417,0.565194,1.061558,1.174570,1.461798,1.408874,1.481201,1.459093,0.712376,1.048476
3,gplvm_cv_results,4,2.0,0.320995,0.293229,0.269274,0.320270,0.605528,0.678806,0.996134,...,0.669706,0.632369,1.077606,1.189914,1.460450,1.415626,1.482142,1.458609,0.722983,1.086913
4,gplvm_cv_results,5,2.0,0.312748,0.280991,0.281759,0.314508,0.613951,0.669990,0.995051,...,0.436164,0.600788,1.010751,1.156243,1.456427,1.409342,1.481237,1.459198,0.709519,1.052128
5,gplvm_ssvi_case_1_cv_results,1,2.0,0.781520,0.777951,0.771646,0.793629,0.846983,0.885799,0.999846,...,1.298944,1.265038,1.316206,1.384578,1.446888,1.428443,1.478717,1.445066,0.931935,1.370017