In [1]:
import pandas as pd
import numpy as np
import os 
from pathlib import Path

In [7]:
seeds = [1, 2, 3, 4, 5]

model_names_and_params = {'gplvm_cv_results':'_latentdim_5_inducing_50_maskseed_42', 
                          'gplvm_ssvi_cv_results':'_latentdim_6_inducing_50_maskseed_42',
                          'knn_cv_results':'_neighbours_5_maskseed_42'
                          }
all_results = []
for model_name, params in model_names_and_params.items():
    for seed in seeds:
        file_path = Path(os.getcwd()) / 'results' / f"{model_name}_seed_{seed}{params}.csv"
        try:
            df = pd.read_csv(file_path)
            df['model'] = model_name
            df['seed'] = seed
            all_results.append(df)
        except FileNotFoundError:
            print(f"File not found: {file_path}")
            continue
    
    
all_results = pd.concat(all_results, ignore_index=True)

In [8]:
all_results

,fold,rmse_dim_train_1,rmse_dim_train_2,rmse_dim_train_3,rmse_dim_train_4,rmse_dim_train_5,rmse_dim_train_6,rmse_dim_train_7,rmse_dim_train_8,rmse_dim_train_9,...,nlpd_dim_test_5,nlpd_dim_test_6,nlpd_dim_test_7,nlpd_dim_test_8,nlpd_dim_test_9,nlpd_dim_test_10,total_rmse_test,total_nlpd_test,model,seed
0,0,0.323042,0.294672,0.253055,0.318260,0.597932,0.650554,0.991951,0.965552,0.996417,...,0.984119,1.084248,1.927232,1.312914,1.414030,1.277597,0.710095,1.023846,gplvm_cv_results,1
1,1,0.382646,0.301757,0.270650,0.281017,0.624491,0.698244,0.993799,0.974867,0.999331,...,0.974271,1.211350,1.391123,1.598409,1.900441,1.843282,0.791671,1.102193,gplvm_cv_results,1
2,2,0.312648,0.293701,0.280025,0.309911,0.640937,0.726087,0.998664,0.953523,0.998042,...,0.942022,1.325293,1.486790,1.284571,1.341893,1.687741,0.728069,1.062021,gplvm_cv_results,1
3,3,0.308531,0.268156,0.232005,0.341261,0.594449,0.670698,0.999245,0.936204,0.999283,...,0.933551,1.060421,1.257192,1.677356,1.171585,1.393617,0.658663,0.983226,gplvm_cv_results,1
4,4,0.308883,0.271354,0.329554,0.294274,0.547064,0.648552,0.997227,0.946897,0.995961,...,1.245436,1.178211,1.234200,1.157928,1.583704,1.096938,0.635705,0.960787,gplvm_cv_results,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0,0.338677,0.446231,0.433115,0.403487,0.728558,0.797176,1.497761,0.981417,1.119046,...,NaN,NaN,NaN,NaN,NaN,NaN,0.776725,NaN,knn_cv_results,5
71,1,0.598357,0.514193,0.414673,0.385065,0.713161,0.797653,0.925096,1.158597,1.548216,...,NaN,NaN,NaN,NaN,NaN,NaN,0.860915,NaN,knn_cv_results,5
72,2,0.428323,0.415687,0.460590,0.473306,0.657378,0.802842,1.071534,0.963744,0.978902,...,NaN,NaN,NaN,NaN,NaN,NaN,0.747436,NaN,knn_cv_results,5
73,3,0.354154,0.475789,0.359231,0.428138,0.725476,0.781231,0.797773,1.271563,0.903642,...,NaN,NaN,NaN,NaN,NaN,NaN,0.711236,NaN,knn_cv_results,5
74,4,0.530660,0.346537,0.459501,0.396404,0.848207,0.792515,0.632031,0.791051,1.126794,...,NaN,NaN,NaN,NaN,NaN,NaN,0.649561,NaN,knn_cv_results,5

In [9]:
# for each seed and model, get the mean rmse and nlpd and print in a nice dataframe
summary_results = all_results.groupby(['model', 'seed']).agg({'total_rmse_test':'mean', 'total_nlpd_test':'mean', 'total_rmse_train':'mean', 'total_nlpd_train':'mean'}).reset_index()
summary_results_std = all_results.groupby(['model', 'seed']).agg({'total_rmse_test':'std', 'total_nlpd_test':'std', 'total_rmse_train':'std', 'total_nlpd_train':'std'}).reset_index()


summary_results

,model,seed,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
0,gplvm_cv_results,1,0.704841,1.026415,0.642103,0.845617
1,gplvm_cv_results,2,0.722832,1.085131,0.646564,0.852760
2,gplvm_cv_results,3,0.712376,1.048476,0.647683,0.857115
3,gplvm_cv_results,4,0.722983,1.086913,0.643600,0.848483
4,gplvm_cv_results,5,0.709519,1.052128,0.642155,0.845188
5,gplvm_ssvi_cv_results,1,0.747530,1.206422,0.617403,1.011546
6,gplvm_ssvi_cv_results,2,0.745539,1.205222,0.616882,1.012091
7,gplvm_ssvi_cv_results,3,0.746510,1.207795,0.614459,1.005323
8,gplvm_ssvi_cv_results,4,0.745953,1.204942,0.618389,1.017554
9,gplvm_ssvi_cv_results,5,0.744452,1.201837,0.614962,1.009481
10,knn_cv_results,1,0.749175,NaN,0.749175,NaN
11,knn_cv_results,2,0.749175,NaN,0.749175,NaN
12,knn_cv_results,3,0.749175,NaN,0.749175,NaN
13,knn_cv_results,4,0.749175,NaN,0.749175,NaN
14,knn_cv_results,5,0.749175,NaN,0.749175,NaN

In [10]:
summary_results_std

,model,seed,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
0,gplvm_cv_results,1,0.061276,0.057422,0.008947,0.017172
1,gplvm_cv_results,2,0.067398,0.068206,0.011075,0.021566
2,gplvm_cv_results,3,0.060796,0.063003,0.008644,0.018807
3,gplvm_cv_results,4,0.053842,0.036255,0.009410,0.019050
4,gplvm_cv_results,5,0.051557,0.022401,0.011704,0.022565
5,gplvm_ssvi_cv_results,1,0.050255,0.099107,0.018070,0.025032
6,gplvm_ssvi_cv_results,2,0.053379,0.104050,0.017298,0.021202
7,gplvm_ssvi_cv_results,3,0.049226,0.100046,0.013659,0.020610
8,gplvm_ssvi_cv_results,4,0.049276,0.096830,0.017344,0.029616
9,gplvm_ssvi_cv_results,5,0.043636,0.091162,0.015995,0.024018
10,knn_cv_results,1,0.078438,NaN,0.078438,NaN
11,knn_cv_results,2,0.078438,NaN,0.078438,NaN
12,knn_cv_results,3,0.078438,NaN,0.078438,NaN
13,knn_cv_results,4,0.078438,NaN,0.078438,NaN
14,knn_cv_results,5,0.078438,NaN,0.078438,NaN

In [14]:
all_results.groupby('model').agg({'total_rmse_test':'mean', 'total_nlpd_test':'mean', 'total_rmse_train':'mean', 'total_nlpd_train':'mean'})

,total_rmse_test,total_nlpd_test,total_rmse_train,total_nlpd_train
model,,,,
gplvm_cv_results,0.714510,1.059813,0.644421,0.849833
gplvm_ssvi_cv_results,0.745997,1.205244,0.616419,1.011199
knn_cv_results,0.749175,NaN,0.749175,NaN

In [30]:
summary_results_incl_dims =all_results.groupby(['model', 'seed']).mean().reset_index()

summary_results_incl_dims

,model,seed,fold,rmse_dim_train_1,rmse_dim_train_2,rmse_dim_train_3,rmse_dim_train_4,rmse_dim_train_5,rmse_dim_train_6,rmse_dim_train_7,...,nlpd_dim_test_3,nlpd_dim_test_4,nlpd_dim_test_5,nlpd_dim_test_6,nlpd_dim_test_7,nlpd_dim_test_8,nlpd_dim_test_9,nlpd_dim_test_10,total_rmse_test,total_nlpd_test
0,gplvm_cv_results,1,2.0,0.327150,0.285928,0.273058,0.308945,0.600975,0.678827,0.996177,...,0.516077,0.518756,1.015880,1.171905,1.459307,1.406236,1.482331,1.459835,0.704841,1.026415
1,gplvm_cv_results,2,2.0,0.314399,0.294489,0.271299,0.321378,0.620572,0.693452,0.995923,...,0.704425,0.688399,1.038123,1.163659,1.462159,1.416006,1.482378,1.460978,0.722832,1.085131
2,gplvm_cv_results,3,2.0,0.322599,0.287723,0.289013,0.321250,0.611258,0.692882,0.997228,...,0.462417,0.565194,1.061558,1.174570,1.461798,1.408874,1.481201,1.459093,0.712376,1.048476
3,gplvm_cv_results,4,2.0,0.320995,0.293229,0.269274,0.320270,0.605528,0.678806,0.996134,...,0.669706,0.632369,1.077606,1.189914,1.460450,1.415626,1.482142,1.458609,0.722983,1.086913
4,gplvm_cv_results,5,2.0,0.312748,0.280991,0.281759,0.314508,0.613951,0.669990,0.995051,...,0.436164,0.600788,1.010751,1.156243,1.456427,1.409342,1.481237,1.459198,0.709519,1.052128
5,gplvm_ssvi_cv_results,1,2.0,0.379885,0.380363,0.329374,0.386092,0.547545,0.637299,0.850575,...,0.779010,0.809843,1.006298,1.253102,1.666535,1.550287,1.688598,1.614102,0.747530,1.206422
6,gplvm_ssvi_cv_results,2,2.0,0.370386,0.377012,0.323265,0.385910,0.555142,0.634975,0.866725,...,0.774606,0.803404,1.008032,1.250197,1.637843,1.562336,1.716184,1.600664,0.745539,1.205222
7,gplvm_ssvi_cv_results,3,2.0,0.373665,0.377380,0.326513,0.383564,0.552293,0.643935,0.853217,...,0.769192,0.793931,1.017671,1.234409,1.653426,1.562389,1.726275,1.632725,0.746510,1.207795
8,gplvm_ssvi_cv_results,4,2.0,0.365416,0.367835,0.322005,0.380631,0.549216,0.642105,0.874978,...,0.782557,0.795945,1.017712,1.210243,1.634337,1.549869,1.733072,1.620471,0.745953,1.204942
9,gplvm_ssvi_cv_results,5,2.0,0.364909,0.373682,0.324531,0.386045,0.555093,0.641852,0.864375,...,0.778625,0.802691,1.018979,1.241898,1.624153,1.541875,1.690912,1.635528,0.744452,1.201837
10,knn_cv_results,1,2.0,0.450034,0.439687,0.425422,0.417280,0.734556,0.794283,0.984839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.749175,NaN
11,knn_cv_results,2,2.0,0.450034,0.439687,0.425422,0.417280,0.734556,0.794283,0.984839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.749175,NaN
12,knn_cv_results,3,2.0,0.450034,0.439687,0.425422,0.417280,0.734556,0.794283,0.984839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.749175,NaN
13,knn_cv_results,4,2.0,0.450034,0.439687,0.425422,0.417280,0.734556,0.794283,0.984839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.749175,NaN
14,knn_cv_results,5,2.0,0.450034,0.439687,0.425422,0.417280,0.734556,0.794283,0.984839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.749175,NaN